### ISSUE TITLE
Add logo header with a relative path

### ISSUE THREAD

**Issue by btzo** [GitbookIO/theme-faq#13]
In the _Add Logos to the header_ example, 
everything works fine when I use a complete URL path, but I want to use a relative path. 

I tried to put the image in the same folder as the `page.html`  , but it did not work.
Any ideas on how to solve this?

**Comment by connor-baer** [comment]
Gitbook includes all the files that are contained in the root directory of your book, except the `_layouts` folder. That's probably why it didn't work for you.

Use a path relative to the root directory of your book. Let's say your logo is in the folder `./gitbook/images/logo.png`. Then you can reference it as such: 

``` html
{% extends template.self %}

{% block faq_header_brand %}
<img src="/gitbook/images/logo.png" height="30" />
{% endblock %}
```

**Comment by btzo** [comment]
It worked, thanks.
