### ISSUE TITLE
i18n not loaded

### ISSUE THREAD

**Issue by xldrkp** [GitbookIO/theme-faq#4]
I created a folder `_i18n`/ in a language subfolder `de/` and put a file inside called `de.json`. This file is a copy of `en.json` that comes with the `theme-faq`. Unfortunately, it is not loaded. But: If I change it from `de.json` to `en.json` in the same folder, the translations work. Could not find out, why it's not loaded, but the workaround helps at the moment.

**Comment by SamyPesse** [comment]
This is going to be fixed in GitBook itself.

It'd be better if the `de.json` is published with the theme itself so that other authors can profit from it, can you make a PR to include it in this repository?

**Comment by SamyPesse** [comment]
Fixed by https://github.com/GitbookIO/gitbook/commit/3234c1e03f5be0ef7d0d6a083a8275cae5b786ff
