### ISSUE TITLE
Is theme-faq compatible with both Markdown and AsciiDoc?

### ISSUE THREAD

**Issue by jaredmorgs** [GitbookIO/theme-faq#7]
I'm getting some issues with the `related` block not rendering in files and I suspect it is because it is expecting .md files not .adoc files.

Is it possible to make the FAQ compatible with AsciiDoc just as GitBook as a whole is?

Is it a matter of declaring `gitbook.asciidoc` in the template?

And adding in `gitbook-asciidoc-css` (or equivalent) into:

```
"devDependencies": {
    "gitbook-markdown-css": "^1.0.1",
    "less": "2.6.0",
    "less-plugin-clean-css": "^1.5.1"
```

**Comment by jaredmorgs** [comment]
Eureka! I have worked out the syntax required for `relates` when writing using AsciiDoc.

In Markdown, you use this syntax:

```
---
related:
    - content/how-can-i-change-theme.md

---
```

In AsciiDoc, you use this syntax:

```
---
related:

- content/how-can-i-change-theme.md

---
```

**Comment by Soreine** [comment]
Hello @jaredmorgs,
Thank you for contributing to make the `theme-faq` better.
I tested locally using the same syntax as in Markdown, and it works well. So I think your problem lied somewhere else (for exemple not disabling the incompatible plugins).
See this Gist https://gist.github.com/Soreine/7bea05f1f453ff4dde6fbd15b0e3f632

The YAML frontmatters used to configure `related` entries uses the YAML syntax, which is independent from Markdown or Asciidoc. If you had to use a different syntax, then it is a bug in the GitBook library.
