### ISSUE TITLE
The number of article in the first parts is wrong

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/theme-faq#9]
The basic FAQ in this [Gist](https://gist.github.com/Soreine/7bea05f1f453ff4dde6fbd15b0e3f632) indicates 2 articles (instead of 1) for the first part and 1 article for the second.

**Comment by juliakm** [comment]
I think that this is an issue with the core GitBook code. Here's an existing pull request that would likely fix the issue:
https://github.com/GitbookIO/gitbook/pull/1517/commits/bd07f1f38bf02806ba1756cf9f8747b8b0eb17a5

**Comment by Soreine** [comment]
Thanks @juliakm, however the PR you mentioned is for a different issue
